dataroot: "/Disk4/xkp/project/BuildingSeg"
modellogdir: "LOG"
modeltype: "HRNet"                            # Unet
batchsize: 2
updatetimes: 2
optimizer: Adam                               #   Adam or SGD
lr: 0.001
updateweights: 4
lr_scheduler: Cos                             #   Cos or Rp
init_ckp: "None"
epoch: 80
CrowdaiData:
  trainimagepath: "/Disk4/xkp/Segmenttion/xkp/Dataset/Crowdai/train/images"
  trainmaskpath:  "/Disk4/xkp/Segmenttion/xkp/Dataset/Crowdai/train/annotation-small.json"
  valimagepath:   "/Disk4/xkp/Segmenttion/xkp/Dataset/Crowdai/val/images"
  valmaskpath:    "/Disk4/xkp/Segmenttion/xkp/Dataset/Crowdai/val/annotation-small.json"
  shape: 128
  padshape: 312
